"""Zambia compliance questions (for Malawian businesses entering Zambia)."""

ZAMBIA_QUESTIONS = ZAMBIA_QUESTIONS = {
    "business_registration": {
        "name": "Business Registration",
        "regulation": "Companies Act No. 10 of 2017",
        "weight": 25,
        "questions": [
            {
                "id": "zm-reg-1",
                "question": "Have you registered your company with the Patents and Companies Registration Agency (PACRA)?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "All companies in Zambia must be registered with PACRA.",
                "resource": "https://www.pacra.org.zm",
            },
            {
                "id": "zm-reg-2",
                "question": "Have you registered your business name with PACRA?",
                "answer_type": "yes_no",
                "critical": False,
                "requirement": "Business names must be registered under the Registration of Business Names Act.",
                "resource": "https://www.pacra.org.zm",
            },
            {
                "id": "zm-reg-3",
                "question": "Do you have a registered office in Zambia?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "A registered office address in Zambia is required under the Companies Act.",
                "resource": "https://www.pacra.org.zm",
            },
            {
                "id": "zm-reg-4",
                "question": "Have you appointed at least two directors (one being a Zambian resident)?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Zambia's Companies Act requires at least one director resident in Zambia.",
                "resource": "https://www.pacra.org.zm",
            },
            {
                "id": "zm-reg-5",
                "question": "Have you obtained sector-specific licenses (zambia agency, etc.)?",
                "answer_type": "yes_no",
                "critical": False,
                "requirement": "Some sectors require licenses (ZRA, ZEMA, ZICTA, banks).",
            },
            {
                "id": "zm-reg-6",
                "question": "Are you aware of the Citizens Economic Empowerment Act requirements?",
                "answer_type": "yes_no",
                "critical": False,
                "requirement": "The CEE Act mandates local ownership participation in certain sectors.",
            },
        ],
    },
    "tax_compliance": {
        "name": "Tax Compliance",
        "regulation": "Income Tax Act No. 12 of 2015 & VAT Act No. 12 of 2018",
        "weight": 25,
        "questions": [
            {
                "id": "zm-tax-1",
                "question": "Have you registered with the Zambia Revenue Authority (ZRA)?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "All businesses must register with ZRA.",
                "resource": "https://www.zra.org.zm",
            },
            {
                "id": "zm-tax-2",
                "question": "Have you obtained a Taxpayer Identification Number (TPIN)?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "A TPIN is required for all business transactions in Zambia.",
                "resource": "https://www.zra.org.zm",
            },
            {
                "id": "zm-tax-3",
                "question": "Are you registered for VAT (if turnover exceeds ZMW 800,000)?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "VAT registration is mandatory when annual turnover exceeds ZMW 800,000.",
                "resource": "https://www.zra.org.zm",
            },
            {
                "id": "zm-tax-4",
                "question": "Do you remit PAYE for your employees?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "PAYE must be deducted and remitted to ZRA.",
            },
            {
                "id": "zm-tax-5",
                "question": "Do you file corporate income tax returns by the 30th of June?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Corporate tax returns due 30 June following end of fiscal year (31 Dec).",
                "resource": "https://www.zra.org.zm",
            },
            {
                "id": "zm-tax-6",
                "question": "Have you applied for a Tax Clearance Certificate (TCC)?",
                "answer_type": "yes_no",
                "critical": False,
                "requirement": "TCC is often required for tenders, loans, and international transactions.",
            },
        ],
    },
    "employment_law": {
        "name": "Employment Law",
        "regulation": "Employment Code Act No. 3 of 2019",
        "weight": 20,
        "questions": [
            {
                "id": "zm-emp-1",
                "question": "Do you use written employment contracts for all employees?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Written contracts are mandatory under the Employment Code Act.",
            },
            {
                "id": "zm-emp-2",
                "question": "Do you comply with minimum wage requirements?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Zambia sets minimum wages through statutory instruments.",
            },
            {
                "id": "zm-emp-3",
                "question": "Do you contribute to the National Pension Scheme Authority (NAPSA)?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Employer and employee contributions to NAPSA are mandatory.",
                "resource": "https://www.napsa.org.zm",
            },
            {
                "id": "zm-emp-4",
                "question": "Do you provide statutory annual leave (minimum 24 days)?",
                "answer_type": "yes_no",
                "critical": False,
                "requirement": "Employees entitled to at least 24 days annual leave per year.",
            },
            {
                "id": "zm-emp-5",
                "question": "Do you follow correct termination and severance procedures?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Terminations must follow legal procedures including notice and severance.",
            },
        ],
    },
    "immigration": {
        "name": "Work Permits & Immigration",
        "regulation": "Immigration and Deportation Act",
        "weight": 15,
        "questions": [
            {
                "id": "zm-imm-1",
                "question": "Have you obtained work permits for foreign employees?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Foreign nationals need work permits to work in Zambia.",
                "resource": "https://www.zambiaimmigration.gov.zm",
            },
            {
                "id": "zm-imm-2",
                "question": "Have you obtained business residence permits for business owners?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Foreign business owners need residence permits to operate in Zambia.",
                "resource": "https://www.zambiaimmigration.gov.zm",
            },
            {
                "id": "zm-imm-3",
                "question": "Do you comply with the employment of expatriates ratio?",
                "answer_type": "yes_no",
                "critical": False,
                "requirement": "Foreign employees should be complemented by local employees.",
            },
        ],
    },
    "data_protection": {
        "name": "Data Protection",
        "regulation": "Data Protection Act No. 3 of 2021",
        "weight": 15,
        "questions": [
            {
                "id": "zm-dpa-1",
                "question": "Have you registered with the Zambia Data Protection Authority (ZDPA)?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Data controllers and processors must register with the ZDPA.",
            },
            {
                "id": "zm-dpa-2",
                "question": "Do you have a privacy policy explaining how personal data is used?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Privacy policies are required under the Data Protection Act.",
            },
            {
                "id": "zm-dpa-3",
                "question": "Do you have procedures for data breach notification?",
                "answer_type": "yes_no",
                "critical": False,
                "requirement": "Data breaches must be reported to the ZDPA.",
            },
            {
                "id": "zm-dpa-4",
                "question": "Do you obtain consent before collecting personal data?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Consent is required for collection of personal data.",
            },
        ],
    },
}

