"""Malawi compliance questions (for Zambian businesses entering Malawi)."""

MALAWI_QUESTIONS = MALAWI_QUESTIONS = {
    "business_registration": {
        "name": "Business Registration",
        "regulation": "Companies Act (Chapter 49:03)",
        "weight": 25,
        "questions": [
            {
                "id": "mw-reg-1",
                "question": "Have you registered your company with the Registrar General's Office in Malawi?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "All companies operating in Malawi must be registered with the Registrar General.",
                "resource": "https://www.registrargeneral.gov.mw",
            },
            {
                "id": "mw-reg-2",
                "question": "Have you registered your business name with the Registrar General?",
                "answer_type": "yes_no",
                "critical": False,
                "requirement": "Trading names must be registered under the Business Names Registration Act.",
                "resource": "https://www.registrargeneral.gov.mw",
            },
            {
                "id": "mw-reg-3",
                "question": "Do you have a registered office address in Malawi?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "A registered office address in Malawi is required under the Companies Act.",
                "resource": "https://www.registrargeneral.gov.mw",
            },
            {
                "id": "mw-reg-4",
                "question": "Have you appointed local directors (at least one Malawi resident)?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Companies Act requires at least one director resident in Malawi.",
                "resource": "https://www.registrargeneral.gov.mw",
            },
            {
                "id": "mw-reg-5",
                "question": "Have you obtained sector-specific licenses for your industry?",
                "answer_type": "yes_no",
                "critical": False,
                "requirement": "Certain industries require additional licensing (telecoms, banking, mining, etc.).",
            },
            {
                "id": "mw-reg-6",
                "question": "Have you filed your annual returns with the Registrar General?",
                "answer_type": "yes_no",
                "critical": False,
                "requirement": "Annual returns must be filed within 60 days of the company's anniversary.",
            },
        ],
    },
    "tax_compliance": {
        "name": "Tax Compliance",
        "regulation": "Income Tax Act (Chapter 44:06) & VAT Act (Chapter 4:05)",
        "weight": 25,
        "questions": [
            {
                "id": "mw-tax-1",
                "question": "Have you registered with the Malawi Revenue Authority (MRA)?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "All businesses must register with MRA for tax purposes.",
                "resource": "https://www.mra.mw",
            },
            {
                "id": "mw-tax-2",
                "question": "Have you obtained a Taxpayer Identification Number (TPIN)?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "A TPIN is required for all tax filings and business transactions.",
                "resource": "https://www.mra.mw",
            },
            {
                "id": "mw-tax-3",
                "question": "Are you registered for VAT (if turnover exceeds MK50 million)?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "VAT registration is mandatory when annual turnover exceeds MK50 million.",
                "resource": "https://www.mra.mw",
            },
            {
                "id": "mw-tax-4",
                "question": "Do you remit PAYE for your employees?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "PAYE must be deducted and remitted to MRA monthly.",
            },
            {
                "id": "mw-tax-5",
                "question": "Do you file corporate income tax returns by the 30th of June?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Corporate tax returns due 30 June following end of fiscal year (31 Dec).",
                "resource": "https://www.mra.mw",
            },
            {
                "id": "mw-tax-6",
                "question": "Have you applied for a Tax Clearance Certificate (TCC)?",
                "answer_type": "yes_no",
                "critical": False,
                "requirement": "TCC is often required for tenders, loans, and international transactions.",
            },
        ],
    },
    "employment_law": {
        "name": "Employment Law",
        "regulation": "Employment Act (Chapter 4:03)",
        "weight": 20,
        "questions": [
            {
                "id": "mw-emp-1",
                "question": "Do you use written employment contracts for all employees?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Employment contracts must be in writing under the Employment Act.",
            },
            {
                "id": "mw-emp-2",
                "question": "Do you comply with minimum wage requirements?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Malawi sets annual minimum wages for various sectors.",
            },
            {
                "id": "mw-emp-3",
                "question": "Do you register employees with the Malawi Social Security (NICO)?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Employers must contribute to social security for employees.",
            },
            {
                "id": "mw-emp-4",
                "question": "Do you provide statutory annual leave (minimum 18 days)?",
                "answer_type": "yes_no",
                "critical": False,
                "requirement": "Employees entitled to at least 18 days annual leave per year.",
            },
            {
                "id": "mw-emp-5",
                "question": "Do you follow correct termination procedures?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Terminations must follow legal procedures including notice periods.",
            },
        ],
    },
    "immigration": {
        "name": "Work Permits & Immigration",
        "regulation": "Immigration Act (Chapter 15:08)",
        "weight": 15,
        "questions": [
            {
                "id": "mw-imm-1",
                "question": "Have you obtained work permits for foreign employees?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Foreign nationals need work permits to work in Malawi.",
                "resource": "https://www.immigration.gov.mw",
            },
            {
                "id": "mw-imm-2",
                "question": "Have you obtained business residence permits for business owners?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Foreign business owners need residence permits to operate in Malawi.",
                "resource": "https://www.immigration.gov.mw",
            },
            {
                "id": "mw-imm-3",
                "question": "Do you have an immigration quota for expatriate employees?",
                "answer_type": "yes_no",
                "critical": False,
                "requirement": "Malawi limits the number of expatriate workers per company.",
            },
        ],
    },
    "data_protection": {
        "name": "Data Protection",
        "regulation": "Data Protection Act (Chapter 4:10)",
        "weight": 15,
        "questions": [
            {
                "id": "mw-dpa-1",
                "question": "Have you registered with the Malawi Data Protection Authority?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Data controllers and processors must register with the authority.",
            },
            {
                "id": "mw-dpa-2",
                "question": "Do you have a privacy policy explaining how personal data is used?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Privacy policies are required under the Data Protection Act.",
            },
            {
                "id": "mw-dpa-3",
                "question": "Do you have procedures for data breach notification?",
                "answer_type": "yes_no",
                "critical": False,
                "requirement": "Data breaches must be reported within 72 hours.",
            },
            {
                "id": "mw-dpa-4",
                "question": "Do you obtain consent before collecting personal data?",
                "answer_type": "yes_no",
                "critical": True,
                "requirement": "Lawful basis and consent required for data processing.",
            },
        ],
    },
}

