"""baseline: full schema

Revision ID: a37e2073248f
Revises: 
Create Date: 2026-09-16 13:08:15.534342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37e2073248f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('origin_country', sa.String(), nullable=False),
    sa.Column('target_country', sa.String(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('compliance_level', sa.String(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('gap_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklists_id'), 'checklists', ['id'], unique=False)
    op.create_table('journeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('origin_country', sa.String(), nullable=False),
    sa.Column('target_country', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('business_model', sa.String(), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journeys_id'), 'journeys', ['id'], unique=False)
    op.create_table('journey_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_phases_id'), 'journey_phases', ['id'], unique=False)
    op.create_table('journey_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('why_needed', sa.Text(), nullable=True),
    sa.Column('authority', sa.String(), nullable=True),
    sa.Column('documents_needed', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.String(), nullable=True),
    sa.Column('estimated_timeline', sa.String(), nullable=True),
    sa.Column('official_source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['journey_phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_steps_id'), 'journey_steps', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('journey_id', sa.Integer(), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('requirement', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['journey_steps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_journey_id'), 'documents', ['journey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_journey_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_journey_steps_id'), table_name='journey_steps')
    op.drop_table('journey_steps')
    op.drop_index(op.f('ix_journey_phases_id'), table_name='journey_phases')
    op.drop_table('journey_phases')
    op.drop_index(op.f('ix_journeys_id'), table_name='journeys')
    op.drop_table('journeys')
    op.drop_index(op.f('ix_checklists_id'), table_name='checklists')
    op.drop_table('checklists')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
